name: Bump and Publish
on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      
      - name: 'Cache node Modules'
        uses: actions/cache@v1
        with:
          path: ~.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci --ignore-scripts
      - run: npm test
  bump-and-build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      
      - name: 'Cache node Modules'
        uses: actions/cache@v1
        with:
          path: ~.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm run prepare

#   release:
#     needs: bump-and-build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Release
#       - uses: actions/setup-node@v1
#       - run: npm run release-ci
